"""initial migration

Revision ID: 1030fa1e4a8
Revises: None
Create Date: 2015-03-06 16:04:48.113093

"""

# revision identifiers, used by Alembic.
revision = '1030fa1e4a8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values5',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values5')
    ### end Alembic commands ###
